#!/bin/bash
# Script para limpiar credenciales del historial de Git
# ADVERTENCIA: Esto reescribe el historial. Úsalo con cuidado.

echo "🔒 Limpiando credenciales del historial de Git..."
echo ""
echo "⚠️  IMPORTANTE:"
echo "   - Esto reescribirá el historial de Git"
echo "   - Todos los colaboradores deberán hacer 'git clone' de nuevo"
echo "   - Los PRs abiertos se romperán"
echo ""
read -p "¿Continuar? (y/n): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    echo "❌ Operación cancelada"
    exit 1
fi

echo ""
echo "📋 Método 1: Usando git filter-repo (RECOMENDADO)"
echo "=============================================="
echo ""
echo "1. Instalar git-filter-repo:"
echo "   pip install git-filter-repo"
echo ""
echo "2. Hacer backup:"
echo "   cd .."
echo "   cp -r backend-sunat backend-sunat-backup"
echo ""
echo "3. Limpiar el archivo del historial:"
echo "   cd backend-sunat"
echo "   git filter-repo --path app/services/scraper_service.py --invert-paths"
echo ""
echo "4. Restaurar el archivo actual (limpio):"
echo "   git checkout HEAD app/services/scraper_service.py"
echo ""
echo "5. Hacer commit y force push:"
echo "   git add app/services/scraper_service.py"
echo "   git commit -m 'chore: restore scraper_service without credentials'"
echo "   git push origin --force --all"
echo ""
echo ""
echo "📋 Método 2: Usando BFG Repo-Cleaner (MÁS FÁCIL)"
echo "=============================================="
echo ""
echo "1. Descargar BFG:"
echo "   https://rtyley.github.io/bfg-repo-cleaner/"
echo ""
echo "2. Crear archivo con las credenciales a eliminar:"
echo "   echo 'Cesar123' > passwords.txt"
echo "   echo 'WEEDIOND' >> passwords.txt"
echo "   echo '10090153566' >> passwords.txt"
echo ""
echo "3. Limpiar el repositorio:"
echo "   java -jar bfg.jar --replace-text passwords.txt"
echo ""
echo "4. Limpiar referencias:"
echo "   git reflog expire --expire=now --all"
echo "   git gc --prune=now --aggressive"
echo ""
echo "5. Force push:"
echo "   git push origin --force --all"
echo ""
echo ""
echo "📋 Método 3: Borrar TODO el historial (NUCLEAR)"
echo "=============================================="
echo ""
echo "1. Crear rama huérfana (sin historial):"
echo "   git checkout --orphan latest_branch"
echo ""
echo "2. Agregar todos los archivos:"
echo "   git add -A"
echo ""
echo "3. Commit inicial:"
echo "   git commit -m 'Initial commit - clean history'"
echo ""
echo "4. Borrar rama main:"
echo "   git branch -D main"
echo ""
echo "5. Renombrar rama actual a main:"
echo "   git branch -m main"
echo ""
echo "6. Force push:"
echo "   git push -f origin main"
echo ""
echo ""
echo "✅ Después de cualquier método:"
echo "   1. Cambiar las contraseñas comprometidas"
echo "   2. Rotar API keys expuestas"
echo "   3. Notificar al equipo para que hagan 'git clone' de nuevo"
echo ""
